"use client";

import { useEffect, useState } from "react";
import { useT } from "./translations";

// Converts the VAPID public key (base64url, as returned by the backend and
// as generated by `web-push generate-vapid-keys`) into the Uint8Array shape
// pushManager.subscribe() requires for applicationServerKey. Standard
// well-known snippet for this — see the W3C Push API / web-push docs.
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; i++) outputArray[i] = rawData.charCodeAt(i);
  return outputArray;
}

type Status = "idle" | "checking" | "subscribed" | "unsupported" | "denied" | "error";

// PushNotificationSettings is the opt-in/opt-out control shown on the
// profile page. It talks directly to the browser's Push API and to the
// backend's /api/push/* endpoints (see backend/internal/server/server.go) —
// no shared state with the rest of the dashboard is needed.
export function PushNotificationSettings() {
  const translate = useT();
  const [status, setStatus] = useState<Status>("checking");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let active = true;
    (async () => {
      if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
        if (active) setStatus("unsupported");
        return;
      }
      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await registration.pushManager.getSubscription();
        if (active) setStatus(subscription ? "subscribed" : "idle");
      } catch {
        if (active) setStatus("idle");
      }
    })();
    return () => { active = false; };
  }, []);

  const enable = async () => {
    setBusy(true);
    try {
      if (Notification.permission === "denied") { setStatus("denied"); return; }
      const permission = await Notification.requestPermission();
      if (permission !== "granted") { setStatus("denied"); return; }

      const keyResponse = await fetch("/api/push/public-key", { credentials: "include" });
      if (!keyResponse.ok) throw new Error("public key unavailable");
      const { publicKey }: { publicKey: string } = await keyResponse.json();

      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey) as BufferSource,
      });

      const subscribeResponse = await fetch("/api/push/subscribe", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(subscription.toJSON()),
      });
      if (!subscribeResponse.ok) throw new Error("subscribe failed");
      setStatus("subscribed");
    } catch {
      setStatus("error");
    } finally {
      setBusy(false);
    }
  };

  const disable = async () => {
    setBusy(true);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await fetch("/api/push/unsubscribe", {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ endpoint: subscription.endpoint }),
        });
        await subscription.unsubscribe();
      }
      setStatus("idle");
    } catch {
      setStatus("error");
    } finally {
      setBusy(false);
    }
  };

  if (status === "unsupported") return null;

  return <section className="profile-facts push-settings">
    <p className="eyebrow">{translate("push_eyebrow")}</p>
    <h2>{translate("push_title")}</h2>
    <p>{translate("push_description")}</p>
    {status === "denied" && <p className="poster-status">{translate("push_permission_denied")}</p>}
    {status === "error" && <p className="poster-status">{translate("push_error")}</p>}
    {status === "subscribed"
      ? <button className="logout-button" onClick={disable} disabled={busy}>{translate(busy ? "push_disabling" : "push_disable")}</button>
      : <button className="logout-button" onClick={enable} disabled={busy || status === "checking"}>{translate(busy ? "push_enabling" : "push_enable")}</button>}
  </section>;
}
