"use client";

import { useEffect, useState } from "react";
import { useT } from "./translations";

// Converts the VAPID public key (base64url, as returned by the backend and
// as generated by `web-push generate-vapid-keys`) into the Uint8Array shape
// pushManager.subscribe() requires for applicationServerKey. Standard
// well-known snippet for this — see the W3C Push API / web-push docs.
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; i++) outputArray[i] = rawData.charCodeAt(i);
  return outputArray;
}

type Status = "idle" | "checking" | "subscribed" | "unsupported" | "denied" | "error";
type Toast = { text: string; detail?: string; autoHide: boolean };

// Rough platform sniff, only used to pick which settings path to show when
// permission is blocked — worst case (an unrecognized UA) it just falls back
// to the generic browser-settings hint below.
function settingsHelpKey(): "push_settings_help_ios" | "push_settings_help_android" | "push_settings_help_generic" {
  const ua = navigator.userAgent;
  if (/iPad|iPhone|iPod/.test(ua) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1)) return "push_settings_help_ios";
  if (/Android/.test(ua)) return "push_settings_help_android";
  return "push_settings_help_generic";
}

// PushNotificationSettings is the opt-in/opt-out control shown on the
// profile page. It talks directly to the browser's Push API and to the
// backend's /api/push/* endpoints (see backend/internal/server/server.go) —
// no shared state with the rest of the dashboard is needed.
export function PushNotificationSettings() {
  const translate = useT();
  const [status, setStatus] = useState<Status>("checking");
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState<Toast | null>(null);

  useEffect(() => {
    if (!toast?.autoHide) return;
    const timer = setTimeout(() => setToast(null), 4000);
    return () => clearTimeout(timer);
  }, [toast]);

  useEffect(() => {
    let active = true;
    (async () => {
      if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
        if (active) setStatus("unsupported");
        return;
      }
      // The server only exposes /api/push/public-key when a VAPID keypair is
      // configured; without one, push is a disabled feature, not an error.
      const keyResponse = await fetch("/api/push/public-key", { credentials: "include" });
      if (!keyResponse.ok) {
        if (active) setStatus("unsupported");
        return;
      }
      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await registration.pushManager.getSubscription();
        if (active) setStatus(subscription ? "subscribed" : "idle");
      } catch {
        if (active) setStatus("idle");
      }
    })();
    return () => { active = false; };
  }, []);

  const enable = async () => {
    setBusy(true);
    try {
      if (Notification.permission === "denied") {
        setStatus("denied");
        setToast({ text: translate("push_permission_denied"), detail: translate(settingsHelpKey()), autoHide: false });
        return;
      }
      const permission = await Notification.requestPermission();
      if (permission !== "granted") {
        setStatus("denied");
        setToast({ text: translate("push_permission_denied"), detail: translate(settingsHelpKey()), autoHide: false });
        return;
      }

      const keyResponse = await fetch("/api/push/public-key", { credentials: "include" });
      if (!keyResponse.ok) throw new Error("public key unavailable");
      const { publicKey }: { publicKey: string } = await keyResponse.json();

      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey) as BufferSource,
      });

      const subscribeResponse = await fetch("/api/push/subscribe", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(subscription.toJSON()),
      });
      if (!subscribeResponse.ok) throw new Error("subscribe failed");
      setStatus("subscribed");
      setToast({ text: translate("push_toast_enabled"), autoHide: true });
    } catch {
      setStatus("error");
      setToast({ text: translate("push_error"), autoHide: true });
    } finally {
      setBusy(false);
    }
  };

  const disable = async () => {
    setBusy(true);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await fetch("/api/push/unsubscribe", {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ endpoint: subscription.endpoint }),
        });
        await subscription.unsubscribe();
      }
      setStatus("idle");
      setToast({ text: translate("push_toast_disabled"), autoHide: true });
    } catch {
      setStatus("error");
      setToast({ text: translate("push_error"), autoHide: true });
    } finally {
      setBusy(false);
    }
  };

  if (status === "unsupported") return null;

  const onToggle = () => { if (status === "subscribed") void disable(); else void enable(); };

  return <>
    <div className="push-settings-row">
      <dt>{translate("push_title")}</dt>
      <dd>
        <label className="toggle-switch">
          <input type="checkbox" checked={status === "subscribed"} onChange={onToggle} disabled={busy || status === "checking" || status === "denied"} />
          <span className="toggle-track"><span className="toggle-thumb" /></span>
        </label>
      </dd>
    </div>
    {toast && <div className="push-toast" role="status">
      <p>{toast.text}</p>
      {toast.detail && <p className="push-toast-detail">{toast.detail}</p>}
      <button type="button" className="push-toast-close" aria-label={translate("close")} onClick={() => setToast(null)}>&times;</button>
    </div>}
  </>;
}
